# print('{0[name]},{1[age]}'.format({'name':'bob'},{'age':24}))

alist = [1,2,5,8,3]
alist.append(50)
print(alist)
print(alist.index(50))
alist.insert(2,20)
print(alist)
alist.remove(50)
print(alist)
alist.append(5)
alist.insert(3,5)
print(alist.index(5))
print(alist)
alist.pop(0)
print(alist)
print(alist.count(5))
alist.sort()
print(alist)
alist.reverse()
print(alist)
alist.extend(range(5))
print(alist)

# atulp = (10,20,80,60,90,40,30,50,50)
# print(atulp)
# print(atulp.count(50))
# print(atulp.index(50))
